#!/usr/bin/env bash
# PreToolUse (Edit|Write): refuse edits to generated files and secrets, and say
# how to regenerate the file instead.
set -uo pipefail

root="${CLAUDE_PROJECT_DIR:-$(pwd)}"
file=$(jq -r '.tool_input.file_path // empty')
[ -n "$file" ] || exit 0
rel="${file#"$root"/}"

deny() {
  jq -n --arg reason "$1" '{
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason: $reason
    }
  }'
  exit 0
}

case "$rel" in
  .env.example | */.env.example) ;;
  .env* | */.env*)
    deny "$rel holds secrets and is off limits. Change .env.example and ask the user to update their own env file." ;;
  pnpm-lock.yaml)
    deny "pnpm-lock.yaml is generated. Change package.json, then run pnpm install (or pnpm add -E <pkg>)." ;;
  */next-env.d.ts)
    deny "$rel is generated by next typegen (pnpm --filter @verisci/web typecheck regenerates it)." ;;
  packages/contracts/soldeer.lock | packages/contracts/dependencies/*)
    deny "$rel is managed by Soldeer. Run forge soldeer install forge-std~<version> in packages/contracts, then update remappings.txt." ;;
  packages/contracts/out/* | packages/contracts/cache/*)
    deny "$rel is Foundry build output. Change the .sol source and run forge build in packages/contracts." ;;
  packages/contracts/broadcast/* | packages/contracts/deployments/* | packages/contracts/src/generated/*)
    deny "$rel is generated from contract builds or deployments. Change the .sol source or the script and regenerate it as packages/contracts/README.md describes." ;;
esac

exit 0
