// Writes RatingController's ABI from the Foundry build as a typed TypeScript module, so
// workspaces built without Foundry (Vercel) can import it.
// Usage: pnpm --filter @verisci/contracts generate:abi (after forge build).
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/**
 * The TypeScript module for an ABI, exported `as const` so viem infers its types.
 * @throws Error when `abi` is not an array, as when the build artifact is missing or stale.
 */
export function renderAbiModule(abi: unknown): string {
  if (!Array.isArray(abi)) {
    throw new Error("The build artifact has no ABI array: run forge build first");
  }
  return [
    "// Generated by tools/generate-abi.ts from the Foundry build.",
    "// Change the contract, then run: pnpm --filter @verisci/contracts generate:abi",
    "",
    "/** RatingController's ABI, `as const` so viem infers every function, event and error. */",
    `export const ratingControllerAbi = ${JSON.stringify(abi, null, 2)} as const;`,
    "",
  ].join("\n");
}

if (import.meta.main) {
  const root = (path: string) => fileURLToPath(new URL(`../${path}`, import.meta.url));
  const artifact = JSON.parse(
    readFileSync(root("out/RatingController.sol/RatingController.json"), "utf8"),
  );
  mkdirSync(root("src/generated"), { recursive: true });
  writeFileSync(root("src/generated/rating-controller-abi.ts"), renderAbiModule(artifact.abi));
}
